name: Playwright Tests
on:
  pull_request:
    branches:
      - candidate

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pnpm Setup
      uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Install dependencies
      run: pnpm install
    - name: Copy .env
      run: cp .env.example .env
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
